GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNyZWVrYW50aCIsImlhdCI6MTY0OTA2OTk1OX0.VUe9tGGVS39WsZqTQkJgzF6Dnb3coiuMyw756D5oVCE
###

GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNyZWVrYW50aCIsImlhdCI6MTY0OTA2OTk1OX0.VUe9tGGVS39WsZqTQkJgzF6Dnb3coiuMyw756D5oVCE
###


GET http://localhost:3000/books/3/

###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "sreekanth",
    "password": "singamalaii",
    "gender":"male",
    "location":"warangal"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "sreekanth",
    "password": "singamalaii"
}